create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists public.system_data (
  key text primary key,
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_system_data_updated_at
on public.system_data(updated_at desc);

create index if not exists idx_system_data_key_prefix_updated
on public.system_data(key text_pattern_ops, updated_at desc);

drop trigger if exists trg_system_data_updated_at on public.system_data;

create trigger trg_system_data_updated_at
before update on public.system_data
for each row execute function public.set_updated_at();

alter table public.system_data enable row level security;
revoke all on public.system_data from anon, authenticated;
comment on table public.system_data is 'Legacy Supabase table. Production uses Cloudflare D1/Worker routes; browser direct access disabled by RLS.';

create table if not exists public.issues (
  id bigint primary key generated by default as identity,
  student_name text not null default '',
  student_class text not null default '',
  school text not null default '',
  issue_type text not null default '',
  description text not null default '',
  contact_info text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists idx_issues_status_created
on public.issues(status, created_at desc);

create index if not exists idx_issues_school_class_status
on public.issues(school, student_class, status, created_at desc);

alter table public.issues enable row level security;
revoke all on public.issues from anon, authenticated;
comment on table public.issues is 'Legacy Supabase table. Production uses authenticated Worker routes; browser direct access disabled by RLS.';

create table if not exists public.system_logs (
  id bigint primary key generated by default as identity,
  operator text,
  action text not null default '',
  details text,
  status text not null default 'normal',
  created_at timestamptz not null default now()
);

create index if not exists idx_system_logs_status_created
on public.system_logs(status, created_at desc);

alter table public.system_logs enable row level security;
revoke all on public.system_logs from anon, authenticated;
comment on table public.system_logs is 'Legacy Supabase table. Production uses authenticated Worker routes; browser direct access disabled by RLS.';

create table if not exists public.system_users (
  username text primary key,
  role text not null default 'guest',
  roles jsonb not null default '[]'::jsonb,
  school text,
  class_name text,
  teacher_name text,
  password_hash text,
  password_scheme text not null default '',
  password_source text not null default '',
  has_password boolean not null default false,
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_system_users_role_school
on public.system_users(role, school, class_name, is_active);

create index if not exists idx_system_users_teacher_name
on public.system_users(teacher_name, is_active);

drop trigger if exists trg_system_users_updated_at on public.system_users;

create trigger trg_system_users_updated_at
before update on public.system_users
for each row execute function public.set_updated_at();

alter table public.system_users enable row level security;
revoke all on public.system_users from anon, authenticated;
comment on table public.system_users is 'Managed by Edge Function only. Browser direct access disabled by RLS.';

create table if not exists public.system_users_staging (
  username text primary key,
  role text not null default 'guest',
  roles jsonb not null default '[]'::jsonb,
  school text,
  class_name text,
  teacher_name text,
  has_password boolean not null default false,
  imported_at timestamptz not null default now()
);

create index if not exists idx_system_users_staging_role_school
on public.system_users_staging(role, school, class_name);

alter table public.system_users_staging enable row level security;
revoke all on public.system_users_staging from anon, authenticated;
comment on table public.system_users_staging is 'Managed by migration tooling and Edge Function only. Browser direct access disabled by RLS.';

create table if not exists public.migration_runs (
  id bigint primary key generated by default as identity,
  source_name text not null,
  dataset_name text not null,
  row_count integer not null default 0,
  detail_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_migration_runs_source_dataset
on public.migration_runs(source_name, dataset_name, created_at desc);

alter table public.migration_runs enable row level security;
revoke all on public.migration_runs from anon, authenticated;
comment on table public.migration_runs is 'Migration audit table. Browser direct access disabled by RLS.';
